import { type NextPage } from "next";
import Head from "next/head";
import { UserButton, SignIn } from "@clerk/nextjs";

import { api } from "~/utils/api";



const Home: NextPage = () => {
  const {data} = api.posts.getAll.useQuery();


  return (
    <>
      <Head>
        <title>Emoter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col justify-center bg-slate-800 ">
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <header className="flex fixed top-0 left-0 right-0 justify-between  py-4 px-6 " >
          <button className="bg-rose-500 text-white p-2 m-2 rounded-xl"
          >Motes</button>
          <h1 className="uppercase text-6xl font-bold text-white">Emoter</h1>
          <div className="flex items-center p-2 m-2">
            <UserButton />
          </div>
        </header>
        <div className="flex flex-col items-center">
          <h2 className="text-4xl font-bold text-white">Posts</h2>
          <div className="flex flex-col items-center">
            {data?.map((post) => (
              <div key={post.id}>{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
