
import Head from "next/head";
import { UserButton, SignIn } from "@clerk/nextjs";

export default function Home() {

  return (
    <>
      <Head>
        <title>Emoter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col justify-center bg-slate-800 ">
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <header className="flex fixed top-0 left-0 right-0 justify-between  py-4 px-6 " >
          <button className="bg-rose-500 text-white p-2 m-2 rounded-xl"
          >Motes</button>
          <h1 className="uppercase text-6xl font-bold text-white">Emoter</h1>
          <div className="flex items-center">
            <UserButton />
          </div>
        </header>
      </main>
    </>
  );
}
